spring:
  data:
    solr:
      host: http://127.0.0.1:8080/solr/
      repositories:
        enabled: false
seo:
  task:
    syn: off
    app: solr
    port: 8080
    server: 172.16.3.78
    collection:  goods,shop,goods,category,categorys,caterev,sku,brand,brandrev
    address: /dataimport?command=full-import&clean=true&commit=true
    logs: /home/3demall/seo/seo-logs/