spring:
  data:
    solr:
      host: http://127.0.0.1:8983/solr/
#      host: http://98.11.0.98/solr/
      repositories:
        enabled: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
seo:
  task:
    syn: off
    app: solr
    port: 8983
    server: 127.0.0.1
    collection:  goods,shop,category,categorys,caterev,sku,brand,brandrev,characteristic
    address: /dataimport?command=full-import&clean=true&commit=true
    logs: /Users/rxbyes/Documents/IDEA/seo-server/seo-logs/suggest/
  keywords:
    stop: /Users/rxbyes/Documents/IDEA/seo-server/data/dictionary/stopwords.txt 
    custom: /Users/rxbyes/Documents/IDEA/seo-server/data/dictionary/custom/CustomDictionary.txt
    table:  /Users/rxbyes/Documents/IDEA/seo-server/data/dictionary/other/CharTable.txt
    core: /Users/rxbyes/Documents/IDEA/seo-server/data/dictionary/CoreNatureDictionary.txt
